### ISSUE TITLE
 Which is the corresponding KBC for reference kbs about sev(-es) pre-attestation?

### ISSUE THREAD

**Issue by haosanzi** [virtee/reference-kbs#6]
This repo is a reference implementation of the [KBS](https://github.com/confidential-containers/kbs/) for sev(-es) platform.  
May I ask which is the corresponding KBC for sev(-es)? If not, is there any related development plan?

**Comment by haosanzi** [comment]
@tylerfanelli @slp

**Comment by slp** [comment]
We don't have a reference KBC, but [libkrun](https://github.com/containers/libkrun) does support acting as a KBC for `reference-kbs` and can be used as a reference.

**Comment by haosanzi** [comment]
Thank you very much. I will close this issue.
